name: slash_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  conditional_builder_null_safety: ^0.0.6
  draggable_bottom_sheet: ^1.0.2
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Noyh
      fonts:
        - asset: assets\fonts\Noyh-Regular.ttf
          weight: 500
        - asset: assets\fonts\Noyh-Black.ttf
          weight: 700
        - asset: assets\fonts\Noyh-Bold.ttf
          weight: 800
        - asset: assets\fonts\Noyh-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\Noyh-Heavy.ttf
          weight: 900
        - asset: assets\fonts\Noyh-Regular.ttf
        - asset: assets\fonts\Noyh-Italic.ttf
          style: italic
        - asset: assets\fonts\Noyh-Light.ttf
          weight: 300
        - asset: assets\fonts\Noyh-Medium.ttf
          weight: 600
        - asset: assets\fonts\Noyh-SemiLight.ttf
          weight: 400
        - asset: assets\fonts\Noyh-Thin.ttf
          weight: 100
